### ISSUE TITLE
IPN URL HTTPS

### ISSUE THREAD

**Issue by alyyousuf7** [stingerpk/woocommerce-easypay#1]
I have used Easypay myself on a website (not WooCommerce) and I noticed that Easypay does not support HTTPS in callback URLS (IPN).
It would be nice if you test it yourself and then update the README. It would be helpful for other people.

You need to take care of one more thing while testing. Easypay doesn't follow 301 redirects as well. If your webserver redirects HTTP requests to HTTPS, your server will not receive the HTTPS request.

Thumbs up for the effort!

**Comment by stingerpk** [comment]
Hey Aly

I am using HTTPS IPN URL for almost an year now without any problems. It might have something to do with how you have setup SSL on your site. I might be able to suggest something if you elaborate your setup.

Thank you for thumbs up. :)
